name: browser-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  dusk-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, sqlite3, pdo_sqlite
          tools: composer

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Prepare test environment
        run: cp .env.dusk .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Start Laravel server
        run: php artisan serve --no-reload --host=127.0.0.1 --port=8000 &
        env:
          APP_ENV: testing
          APP_URL: http://127.0.0.1:8000

      - name: Install ChromeDriver for Dusk
        run: php artisan dusk:chrome-driver --detect

      - name: Run Laravel Dusk tests
        run: php artisan dusk
        env:
          APP_URL: http://127.0.0.1:8000

      - name: Upload failed Dusk screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dusk-screenshots
          path: tests/Browser/screenshots
